### ISSUE TITLE
Looking forward to your excellent work open source.

### ISSUE THREAD

**Issue by NingYuanxiang** [sukjunhwang/VITA#1]

**Comment by sukjunhwang** [comment]
Hi @NingYuanxiang ,

We will start refining the code after returning from CVPR, and the code will surely be publicly available.
We appreciate your patience and interest in our work!

**Comment by manhkhanhad** [comment]
Any update on the code release? It's more than one month after the CVPR 2022 conference.

**Comment by sukjunhwang** [comment]
Hi @manhkhanhad ,

We are working on it and our team's current plan is to release the code after the rebuttal, which ends in a few weeks.
Thank you for your patience.

**Comment by sukjunhwang** [comment]
Hi all, please check the released code. Thank you
