### ISSUE TITLE
COCO pretrained weight

### ISSUE THREAD

**Issue by fanghaook** [sukjunhwang/VITA#10]
How to get the COCO pretrained weights, such as vita_r50_coco.pth?
Does it directly convert the pkl file provided by the mask2former project into the pth file? 
Or train the whole VITA on coco? If so, why should we train coco again when training youtube-vis?

**Comment by sukjunhwang** [comment]
Hi @fanghaook and @lxtGH ,

First, vita_r50_coco.pth is obtained by pretraining the whole VITA on COCO. When training YTVIS, COCO is not being used for image-wise segmentation, rather used for video understanding; COCO makes pseudo videos.

Second, VITA achieves 48.8 AP on ResNet-50 without COCO pseudo labels.

Thank you :)

**Comment by sukjunhwang** [comment]
Hi @lxtGH ,

Thank you for your feedback. ResNet-50 result is fairly reported in Figure-5 in our paper. We will try to report Swin when we have available resources.
As training configurations are available on our git repo, it would also be great if you could share the results :)
