### ISSUE TITLE
ytvis_2019 submit error

### ISSUE THREAD

**Issue by nanle771** [sukjunhwang/VITA#12]
When I submit the result. json file derived from the author's model and my own trained model to Codalab（ https://codalab.lisn.upsaclay.fr/competitions/7682#participate -submit_ Results), the following error occurred:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted.  Memory limited without swap.
Running command git clone -q  https://github.com/youtubevos/cocoapi.git  /tmp/pip-install-rtgaknkx/pycocotools
Traceback (most recent call last):
File "/tmp/codalab/tmppYOyAn/run/program/evaluate.py", line 68, in 
res = gts.loadRes(submit_file)
File "/opt/conda/lib/python3.7/site-packages/pycocotools/ytvos.py", line 217, in loadRes
anns = json.load(open(resFile))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmppYOyAn/run/input/res/results.json'

**Comment by sukjunhwang** [comment]
Each result Json file should be archived to a .zip file before getting submitted to the codalab server. Could you please check if it follows the Codalab submission policies? If it already satisfies all, please let me know

**Comment by nanle771** [comment]
> 

This problem has been resolved because I did not adequately train the model, and I increased SOLVER.MAX_ ITER has obtained the correct results, thank you for your answer
