### ISSUE TITLE
about data preparation

### ISSUE THREAD

**Issue by chen742** [sukjunhwang/VITA#14]
Dear Sir,

Thanks for your outstanding work!

I would like to know how to find convert_coco2ytvis.py file, I did not see it in your repo.

**Comment by sukjunhwang** [comment]
Hi @chen742 ,

If I am getting you right, I believe it's at the root folder of this repo.

**Comment by chen742** [comment]
Dear @sukjunhwang 

Thanks for your prompt reply, I got it!
