### ISSUE TITLE
self.training when calling swin attention in object encoder

### ISSUE THREAD

**Issue by bio-mlhui** [sukjunhwang/VITA#15]
In vita.py of implementation `encode_frame_query`, why the logic is `if  self.training or layer_idx %2 == 0`, since i think adding `self.training` will always direct to vanilla `window_attn` during training, which will make swin attention ineffective. Although all configs files use clip size of 6 and window size 6, this seems wrong to me. Can you explain?

**Comment by cilinyan** [comment]
I'm as confused about this as you are. I don't know if there is a result of deleting self.training.

**Comment by bio-mlhui** [comment]
During training (clip 6 window 6), removing `self.training` will shift window, which is wrong, since under setting of `clip=window`, swin is equivalent to vanilla self-attention.  Then, Swin is only effective at inference. However, video-swin/swin attention is proposed for setting `window >clip`. Also, the video-wwin paper says they use clip32 window8 during training. If VITA contributes by using video-swin/swin to handle temporality, i think they should use the same clip-window setting during training.

**Comment by bio-mlhui** [comment]
During training (clip 6 window 6), removing self.training will shift half-window layer-by-layer, which is wrong, since under setting of clip=window, swin is equivalent to vanilla self-attention. Then, Swin is only effective at inference. However, video-swin/swin attention is proposed for setting window >clip. Also, the video-wwin paper says they use clip32 window8 during training. If VITA contributes by using video-swin/swin to handle temporality, i think they should use the same clip-window setting during training.

**Comment by bio-mlhui** [comment]
During training (clip6 window6), removing self.training will shift half-window layer-by-layer, which is wrong, since under setting of `clip=window`, swin is equivalent to vanilla self-attention. Then, Swin is only effective at **inference**. However, video-swin/swin attention is proposed for setting `window >clip`. Also, the video-swin paper says they use clip32 window8 during training. If VITA contributes by using video-swin/swin to handle temporality, i think they should use the same clip>window setting during training.

**Comment by bio-mlhui** [comment]
During training (clip6 window6), removing self.training will shift half-window layer-by-layer, which is wrong, since under setting of clip=window, swin is equivalent to vanilla self-attention. Then, Swin is only effective at inference. However, video-swin/swin attention is proposed for setting window <clip. Also, the video-swin paper says they use clip32 window8 during training. If VITA contributes by using video-swin/swin to handle temporality, i think they should use the same clip>window setting during training.

**Comment by bio-mlhui** [comment]
During training (clip6 window6), removing self.training will shift half-window layer-by-layer, which is wrong, since under setting of `clip=window`, swin is equivalent to vanilla self-attention. Then, Swin is only effective at **inference**. However, video-swin/swin attention is proposed for setting `window<clip`. Also, the video-swin paper says they use clip32 window8 during training. If VITA contributes by using video-swin/swin to handle temporality, i think they should use the same `clip>window` setting during training.

**Comment by bio-mlhui** [comment]
I think the object encoder is just a **tracking** module. Naturally, the tracking task can be simply decomposed into tracking inside each window (overlapped) and link the tracking result. The tracking task work well as long as the tracking module can link similar objects in each window, since the windows are overlapped. However, for tasks such as the action classification, where the classfication result must be confirmed using the whole video context,  the swin attention thus must output a feature which path-connected to all frame feature maps, and the model then use that feature to classification. This global-path-connect capability must be learned by training. And the tracking task does not need this capability. Therefore, in video-swin paper, they use `window<clip` to train action classification task. Under this interpretation, this inference-training inconsistency is not wrong.

**Comment by bio-mlhui** [comment]
I think the object encoder is just a **tracking** module. Naturally, the tracking task can be simply decomposed into tracking inside each window (overlapped) and link the tracking result. The tracking task work well as long as the tracking module can link similar objects in each window, since the windows are overlapped. However, for tasks such as the action classification, where the classfication result must be confirmed using the whole video context, the swin attention thus must output a feature which path-connected to all frame feature maps, and the model then use that feature to classification. This global-path-connect capability must be learned by training. And the tracking task (video instance segmentation) does not need this capability. Therefore, in video-swin paper, they use window<clip to train action classification task. Under this interpretation, this inference-training inconsistency is not wrong.

**Comment by bio-mlhui** [comment]
I think the object encoder is just a tracking module. Naturally, the tracking task can be simply decomposed into tracking inside each window (overlapped) and link the tracking result. The tracking task work well as long as the tracking module can link similar objects in each window, since the windows are overlapped. However, for tasks such as the action classification, where the classfication result must be confirmed using the whole video context, the swin attention thus must output a feature which path-connected to all frame feature maps, and the model then use that feature to classification. This global-path-connect capability must be learned by training. And the tracking task (video instance segmentation) does not need this capability. Therefore, in video-swin paper, they use window<clip to train action classification task. Under this interpretation, i think this inference-training inconsistency may be verified.

**Comment by cilinyan** [comment]
get it, thanks
