### ISSUE TITLE
how to visualize the segmentation result and generate the bitmask png for trained model?

### ISSUE THREAD

**Issue by f414158949** [sukjunhwang/VITA#2]

**Comment by miranheo** [comment]
Hi, @f414158949 

You can visualize your trained model by running demo.py.
For example, if you want to visualize video 0062f687f1 in the YouTubeVIS-2019 validation set with a provided pertained weight, you can run the script below.

```bash
python demo_vita/demo.py --config-file configs/youtubevis_2019/vita_R50_bs8.yaml \
--input datasets/ytvis_2019/valid/JPEGImages/0062f687f1/*.jpg \
--output output/demo --save-frames True \
--opts MODEL.WEIGHTS vita_r50_ytvis2019.pth
```

However, the above script generates overlay masks on the input image. Therefore, if you want to visualize the bitmask, you may need to modify demo.py. The simplest way is to use "pred_masks" in the `predictions` variable.

**Comment by miranheo** [comment]
If you have any further questions, please feel free to contact us by email - miran@yonsei.ac.kr.
