### ISSUE TITLE
How to get the train.json, val.json of ytvis_2021?

### ISSUE THREAD

**Issue by xjtuwh** [sukjunhwang/VITA#4]
FileNotFoundError: [Errno 2] No such file or directory: '/media/wuhan/disk1/dataset/ytvis_2021/train.json'

**Comment by sukjunhwang** [comment]
Hi, @xjtuwh ,

You can download it from the official challenge site.
Please check https://youtube-vos.org 

Thank you

**Comment by xjtuwh** [comment]
![image](https://user-images.githubusercontent.com/22558591/192132131-ef58e7c9-0791-481a-83f6-abc595e34c7d.png)
![image](https://user-images.githubusercontent.com/22558591/192132148-72193ae4-b1b2-4624-ba8b-3701284435b5.png)
I cannot find the train.json, just an instance .json, is it the same?

**Comment by sukjunhwang** [comment]
It's probably included in the compressed file.
Please check if train.json is in train.zip.

**Comment by xjtuwh** [comment]
![image](https://user-images.githubusercontent.com/22558591/192132230-0faeac18-7354-4959-bed3-e83ee406b4bc.png)

**Comment by xjtuwh** [comment]
A json file and a JPEGImages files

**Comment by sukjunhwang** [comment]
Yes, I also checked the files and it seems like the annotation files are missing which I think the organizers removed by mistake.
Could you please ask Linjie Yang (https://sites.google.com/site/linjieyang89/) to recover the links for the annotations?

**Comment by xjtuwh** [comment]
OK, thank you~

**Comment by fbragman** [comment]
@xjtuwh Any luck? Annotations files for VIS2021 are still not available for download.

Thanks!
