### ISSUE TITLE
Error in detectron2

### ISSUE THREAD

**Issue by fanghaook** [sukjunhwang/VITA#7]
I installed the environment completely according to your requirements, but there was a problem during training：

Traceback (most recent call last):
  File "/home/fanghao/anaconda3/envs/vita/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/fanghao/detectron2/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/fanghao/VITA/train_net_vita.py", line 306, in main
    return trainer.train()
  File "/home/fanghao/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/fanghao/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/fanghao/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/fanghao/detectron2/detectron2/engine/train_loop.py", line 421, in run_step
    with autocast(dtype=self.precision):
TypeError: __init__() got an unexpected keyword argument 'dtype'

I can train after deleting “dtype=self. precision” in detectron2/detectron2/engine/train_loop.py, but it's not clear if this will have an impact. I suspect that the problem is caused by the difference between the author's current version and the current version of detectron2. I suggest you run the project again under the latest detectron2 to verify whether you will encounter the same problems as me.
If you have the same problem, I hope you can update your code to adapt to the latest detectron2, or embed your current detectron2 version into the VITA project, similar to the VNext project. Of course, it is OK to simply delete "dtype=self. precision".

thank you！

**Comment by sukjunhwang** [comment]
Hi @fanghaook ,

Given the error message, I suspect the problem is not from our code; the error happens in ```detectron2/detectron2/engine/train_loop.py```).
I believe it's from a mismatch between PyTorch and detectron2.
Could you please check your PyTorch and detectron2 versions?

thank you

**Comment by fanghaook** [comment]
At first, I ran it with pytorch 1.12. The program reported that pytorch was missing some files. It may be that the new version of pytorch does not fit. Then I installed it in exactly the same way as INSTALL.md, so the version of pytorch is 1.9. The version of detectron2 is the latest version, which was clone 4 days ago.
You can try the latest version of pytorch and pytorch 1.9, add the latest version of detectron2 to verify whether the training file can be run.

thank you

**Comment by fanghaook** [comment]
Hi @sukjunhwang 

Another problem is the training parameters. If I only have two GPUs, I have to modify the IMS_ PER_ BATCH is 2. How do I modify other parameters to reproduce the results of the author's 8 gpus as much as possible. Parameters that can be modified, such as BASE_ LR: 0.00005，STEPS: (75000,)，MAX_ ITER: 140000.

thank you

**Comment by sukjunhwang** [comment]
Hi @fanghaook ,

As we use AdamW for the optimizer, not SGD, it is a bit complicated to say the optimal learning rate for each batch size.
I suggest you to follow this [paper](https://arxiv.org/abs/1711.00489) to find an adequate setting for your system.
(For an initial guess, I would just keep lr and multiply 4 to the steps and max_iter)

For the former question you raised, I will keep this issue opened and look for the error a bit later on :)
Thank you
